---
abstract: 'simple email creation with auto text and html multipart body'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Simple-Markdown
provides:
  Email::Simple::Markdown:
    file: lib/Email/Simple/Markdown.pm
    version: v0.2.0
requires:
  Email::Abstract: 0
  Email::MIME: 0
  Email::Simple: 0
  Text::MultiMarkdown: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Email-Simple-Markdown
  homepage: http://search.cpan.org/dist/Email-Simple-Markdown/
  repository: https://github.com/yanick/Email-Simple-Markdown.git
version: 0.2.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
